/**
 * Dev Port Sync
 *
 * Writes the API server URL to a file so the frontend can discover it.
 * Only runs in development mode.
 */

import app from '@adonisjs/core/services/app'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const currentDir = dirname(fileURLToPath(import.meta.url))

if (!app.inProduction) {
  // Wait for server to be ready, then write config
  app.ready(async () => {
    try {
      const server = await app.container.make('server')
      const address = server.getNodeServer()?.address()

      if (address && typeof address === 'object' && 'port' in address) {
        const port = address.port
        const host = process.env.HOST || 'localhost'
        const apiUrl = `http://${host}:${port}`

        // Write to shared location for frontend to read
        // NOTE: USER_COOKIE_SECRET must match API's secret for cookie verification
        const envPath = resolve(currentDir, '../../web/.env.development.local')
        const userCookieSecret = process.env.USER_COOKIE_SECRET || ''
        const envContent = [
          '# Auto-generated by API server - do not edit',
          `NEXT_PUBLIC_API_URL=${apiUrl}`,
          `API_URL=${apiUrl}`,
          '',
          '# Cookie signing secret (synced from API)',
          `USER_COOKIE_SECRET=${userCookieSecret}`,
          '',
        ].join('\n')
        writeFileSync(envPath, envContent)

        console.log(`[DevPortSync] Wrote API config to ${envPath}: ${apiUrl}`)
      }
    } catch (error) {
      // Non-fatal - just log and continue
      console.warn('[DevPortSync] Could not sync config:', error)
    }
  })
}
